version: "2.2"

services:
  signalk-server-node:
    build: .
    image: signalk-server-node
    container_name: signalk-server-node
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/../signalk_conf:/home/node/.signalk
      - /dev:/dev/hostdev
    entrypoint: /home/node/signalk/bin/signalk-server --securityenabled
    privileged: true
    logging:
      options:
        max-size: 10m
