version: "2.2"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8086:8086"
    volumes:
      - $PWD/../signalk_volume/influxdb:/var/lib/influxdb
    logging:
      options:
        max-size: 10m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    network_mode: bridge
    user: "0:0"
    ports:
      - "3001:3000"
    links:
      - influxdb
    volumes:
      - $PWD/../signalk_volume/grafana/data:/var/lib/grafana
      - $PWD/../signalk_volume/grafana/conf:/usr/share/grafana/conf
    logging:
      options:
        max-size: 10m

  signalk-server:
    image: kgustafs/signalk-server:latest
    container_name: signalk-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/../signalk_conf:/home/node/.signalk
      - /dev:/dev/hostdev
    entrypoint: sh /home/node/signalk/startup.sh
    privileged: true
    logging:
      options:
        max-size: 10m
