version: "2.2"

services:
  signalk-server:
    image: kgustafs/signalk-server:latest
    container_name: signalk-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/../signalk_conf:/home/node/.signalk
      - /dev:/dev/hostdev
    entrypoint: sh /home/node/signalk/startup.sh
    privileged: true
    logging:
      options:
        max-size: 10m
