version: "2.2"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8086:8086"
    volumes:
      - $PWD/../signalk_volume/influxdb:/var/lib/influxdb
    logging:
      options:
        max-size: 10m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    network_mode: bridge
    user: "0:0"
    ports:
      - "3001:3000"
    links:
      - influxdb
    volumes:
      - $PWD/../signalk_volume/grafana/data:/var/lib/grafana
      - $PWD/../signalk_volume/grafana/conf:/usr/share/grafana/conf
    logging:
      options:
        max-size: 10m

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: unless-stopped
    network_mode: host
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - $PWD/../signalk_volume/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    logging:
      options:
        max-size: 10m

  signalk-server:
    build: .
    image: signalk-server
    container_name: signalk-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/../signalk_conf:/home/node/.signalk
      - /dev:/dev/hostdev
    entrypoint: sh /home/node/signalk/startup.sh
    privileged: true
    logging:
      options:
        max-size: 10m
